### ISSUE TITLE
Why not use webgl2 to build

### ISSUE THREAD

**Issue by rexhang** [arianrhodsandlot/retro-assembly#6]
![image](https://github.com/arianrhodsandlot/retro-assembly/assets/14832793/286b9ec9-a7d4-462d-800d-1ed4d64d3519)

but our current...

<img width="578" alt="475c8992eab9e49b7765bd0d51694ec" src="https://github.com/arianrhodsandlot/retro-assembly/assets/14832793/f17606d7-15fc-4b96-bebd-f05ed9d4eb68">

**Comment by rexhang** [comment]
> 

webgl2 is significantly smoother

**Comment by arianrhodsandlot** [comment]
For this project, using the original RetroArch cores (which we are building on top of) and keeping changes/patches to them as small as possible is preferred at current stage. Using WebGL2 seems to require some changes in the build scripts of RetroArch. Maintaining these changes may require additional effort and could result in things breaking more easily. So adoption of WebGL2 may not occur unless its adopted by the upstream.
